#!/bin/bash

WIKIDUMP_BASE=`dirname "$0"`

while [ $# -gt 0 ]; do
    if [ $1 == "--configfile" ]; then
	CONFIGFILE="$2"
	shift; shift
    elif [ $1 == "--basedir" ]; then
	WIKIDUMP_BASE="$2"
	shift; shift
    elif [ $1 == "--sleep" ]; then
	SLEEP_INTERVAL="$2"
	shift; shift
    else
	echo "$0: Unknown option $1"
	echo "Usage: $0 [--configfile filename] [--basedir dir] [--sleep seconds]"
	echo "--configfile   use specified file for config file (default: wikidump.conf)"
	echo "--basedir      scripts and files are relative to this dir (default: location of this script)"
	echo "--sleep        time to sleep between runs (default 15)"
	exit 1
    fi
done

pythonargs=( "./monitor.py" )
if [ ! -z "$CONFIGFILE" ]; then
    pythonargs=( "${pythonargs[@]}" "$CONFIGFILE" )
fi

while true; do
#    echo ""
#    echo "Sweeping!"
#    echo python3 ${pythonargs[@]}
    cd ${WIKIDUMP_BASE}
    python3 ${pythonargs[@]}
    if [ -z "$SLEEP_INTERVAL" ]; then
#    echo "sleeping"
        sleep 15
    else
	sleep $SLEEP_INTERVAL
    fi
done
