#!/bin/bash

# number of failures of worker.py in a row before we decide
# something serious is broken and we refuse to run
MAXFAILS=3
failures=0

WIKIDUMP_BASE=`dirname "$0"`

if [ ! -z "$1" ]; then
    configFile="$1"
fi

while true; do
    if [ -e "$WIKIDUMP_BASE/maintenance.txt" ]; then
	echo "in maintenance mode, sleeping 5 minutes"
	sleep 300
    else
	if [ ! -z "$configFile" ]; then
	    python $WIKIDUMP_BASE/worker.py "--configfile" "$configFile"
	else
	    python $WIKIDUMP_BASE/worker.py
	fi
	if [ $? -ne 0 ]; then
	    failures=$(($failures+1))
	    if [ $failures -gt $MAXFAILS ]; then
		echo "more than $MAXFAILS failures in a row, halting."
		exit 1
	    fi
	fi
	echo "sleeping"
	sleep 30
    fi
done
