#!/bin/bash

WIKIDUMP_BASE=`dirname "$0"`

if [ ! -z "$1" ]; then
    configFile="$1"
else
    configFile=""
fi

if [ ! -z "$2" ]; then
    if [ "$2" == "verbose" ]; then
	verbose="--verbose"
    else
	echo "Unknown option $2"
	exit 1
    fi
fi

while true; do
	echo ""
	echo "Sweeping!"
	python $WIKIDUMP_BASE/incrmonitor.py "$configFile" "$verbose"
	echo "sleeping"
	sleep 15
done
